#!/bin/bash
THIS_FILE=$(python -c "import os; print os.path.normcase(os.path.normpath(os.path.realpath(os.path.abspath('''$0'''))))")
THIS_DIR=$(dirname "$THIS_FILE")
if [[ -z $DEMO_SLAM ]]; then
    DEMO_SLAM=demo_slam
fi
cmd=("$DEMO_SLAM" --replay=1  --robot=0 --pause=0 --dump=1 --log=1 --render-all=0 --disp-2d=1 --disp-3d=1 --data-path="$THIS_DIR" --config-setup=@/setup.cfg --config-estimation=@/estimation.cfg --rand-seed=0 --freq=100)
echo "${cmd[@]}"
eval "${cmd[@]}"